%loadpy yacc.py

r0 = Rule('e : t e\'', 0)
r1 = Rule('e\' : PLUS t e\'', 1)
r2 = Rule('e\' : epsilon', 2)
r3 = Rule('t : f t\'', 3)
r4 = Rule('t\' : TIMES f t\'', 4)
r5 = Rule('t\' : epsilon', 5)
r6 = Rule('f : LPAREN e RPAREN', 6)
r7 = Rule('f : ID', 7)

rules = Rules()
rules.add(r0)
rules.add(r1)
rules.add(r2)
rules.add(r3)
rules.add(r4)
rules.add(r5)
rules.add(r6)
rules.add(r7)
rules.set_start_rule(r0)

print rules

rules.first('e')
# >>> set(['ID', 'LPAREN'])
rules.first('t')
# >>> set(['ID', 'LPAREN'])
rules.first('f')
# >>> set(['ID', 'LPAREN'])
rules.first('e\'')
# >>> set(['epsilon', 'PLUS'])
rules.first('t\'')
# >>> set(['epsilon', 'TIMES'])

rules.follow('e')
# >>> set(['RPAREN', '$'])
rules.follow('e\'')
# >>> set(['RPAREN', '$'])
rules.follow('t')
# >>> set(['PLUS', 'RPAREN', '$'])
rules.follow('t\'')
# >>> set(['PLUS', 'RPAREN', '$'])
rules.follow('f')
# >>> set(['PLUS', 'RPAREN', '$', 'TIMES'])

parser = LL1Parser(None, rules)
parser.__print_parsing_table__()
